# Generated by Django 4.1 on 2024-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('UID', models.IntegerField(primary_key=True, serialize=False)),
                ('UName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('UType', models.CharField(max_length=50)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=50, null=True)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Cdatatime', models.DateTimeField()),
            ],
        ),
    ]
