# Generated by Django 4.2.14 on 2024-08-08 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
