# Generated by Django 4.2.14 on 2024-08-08 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_userinfo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UID',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
