# Generated by Django 4.2.14 on 2024-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_userinfo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
