# Generated by Django 4.2.14 on 2024-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_userinfo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Cdatatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
