# Generated by Django 4.2.14 on 2024-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_userinfo_cdatatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UType',
            field=models.CharField(blank=True, choices=[('OPERATOR', 'OPERATOR'), ('ADMIN', 'ADMIN'), ('FACULTY', 'FACULTY')], max_length=50),
        ),
    ]
